# Koyeb Deployment Configuration
# This file enables one-click deployment to Koyeb via Git Push
#
# Usage:
#   1. Push your code to GitHub
#   2. Connect your repo to Koyeb
#   3. Koyeb will automatically detect this file and deploy

name: rag-starter-kit
services:
  - name: rag-app
    type: web
    build:
      type: dockerfile
      dockerfile_path: Dockerfile
    env:
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: SUPABASE_SERVICE_KEY
        value: ${SUPABASE_SERVICE_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
    ports:
      - port: 8501
        http:
          paths:
            - /
    healthcheck:
      path: /_stcore/health
      interval: 30s
      timeout: 10s
      retries: 3
